@include('site.home.partials.categories', ['landing' => $landing])
@include('site.home.partials.deals', ['landing' => $landing])
@include('site.home.partials.destinations', ['landing' => $landing])
@include('site.home.partials.agencies', ['landing' => $landing])
@include('site.home.partials.reels', ['landing' => $landing])
@include('site.home.partials.process', ['landing' => $landing])
@include('site.home.partials.dishes')
@include('site.home.partials.testimonials', ['landing' => $landing])
@include('site.home.partials.agency-cta')
@include('site.home.partials.faq', ['landing' => $landing])
@include('site.home.partials.newsletter')
